services:
  knight-wallet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app

  tests:
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - ./app:/app
    command: ["python", "-m", "unittest", "discover", "-s", ".", "-p", "test_*.py"]
